# ----------------add-in scheduling capabilities
FROM sql2eh:latest AS sql2ehScheduled

RUN apt-get update && apt-get -y install cron

COPY sql2eh-cron /etc/cron.d/sql2eh-cron
RUN chmod 0744 /etc/cron.d/sql2eh-cron
RUN crontab /etc/cron.d/sql2eh-cron

RUN touch /var/log/cron.log

#CMD cron && tail -f /var/log/cron.log
CMD ["cron","-f"]
